/** Ed25519 public key that verifies Lamplight extension packages (generated by scripts/extension-key.mjs). */
export const EXTENSION_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAlCAMHm9yVNwJNd0d5RHcBDeB1yfJc0Amfk8n4rrlACg=
-----END PUBLIC KEY-----`;
