// Creates the Ed25519 key pair that signs Lamplight extensions: node scripts/extension-key.mjs
// The private key stays outside the repository; the public key is embedded in the app.
import { generateKeyPairSync } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const privatePath = process.env.LAMPLIGHT_EXT_SIGNING_KEY ?? join(homedir(), ".config", "lamplight", "extension-signing-key.pem");
const publicTs = join(import.meta.dirname, "..", "src", "main", "extensions", "publicKey.ts");

if (existsSync(privatePath)) {
  console.error(`${privatePath} already exists; delete it first to rotate the key (old extensions will stop verifying)`);
  process.exit(1);
}
const { publicKey, privateKey } = generateKeyPairSync("ed25519");
mkdirSync(dirname(privatePath), { recursive: true, mode: 0o700 });
writeFileSync(privatePath, privateKey.export({ type: "pkcs8", format: "pem" }), { mode: 0o600 });
writeFileSync(publicTs, `/** Ed25519 public key that verifies Lamplight extension packages (generated by scripts/extension-key.mjs). */
export const EXTENSION_PUBLIC_KEY = \`${publicKey.export({ type: "spki", format: "pem" }).toString().trim()}\`;
`);
console.log(`private key: ${privatePath}\npublic key:  ${publicTs}`);
